name: Kulta ja Pupsik
favicon: null
layout_spectrum: 0.9378958735615015
typography_spectrum: 0.07129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9b14d'
    - '#232838'
    - '#c7d8ed'
    - '#495e7f'
    - '#bf6324'
  brandStrength: 0.517775577493012
  lightness: 1
  saturation: 0.8460433781147003
  rhythmicContrast: 1
purpose: []
