name: Kulta ja Pupsik
favicon: null
layout_spectrum: 0.75871
typography_spectrum: 0.13873
title: Slava and Joanne tying the knot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9b14d'
    - '#232838'
    - '#c7d8ed'
    - '#495e7f'
    - '#bf6324'
  brandStrength: 0
  lightness: 1
  saturation: 0.8460433781147003
  rhythmicContrast: 1
purpose: []
